resources:
  - name: ios_hello_world
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: SyntacticStructures/ios-hello-world

pipelines:
  - name: BUILD_IOS
    steps:
      - name: BUILD_IOS_0001
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          inputResources:
            - name: ios_hello_world
        execution:
          onExecute:
            - pushd $res_ios_hello_world_resourcePath
            - xcodebuild build -sdk "iphonesimulator"
            - pushd $res_ios_hello_world_resourcePath/build/Release-iphonesimulator/
            - tar czf ios-hello-world-${run_number}.tar.gz HelloWorld.app
            - jfrog rt upload ios-hello-world-${run_number}.tar.gz ios-hello-world-releases
