pipelines:
  - name: taylorl2
    steps:
      - name: taylorl_0001
        type: Bash
        configuration:
          integrations:
            - name: int_slack
        execution:
          onExecute:
            - send_notification int_slack --text "starting test_step_1"
