pipelines:
  - name: taylorl
    steps:
      - name: taylorl_0001
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - uname -m
