pipelines:
  - name: S_Bash_Util_8631_002
    configuration:
      affinityGroup: agroup
    steps:
      - name: S_Bash_Util_8631_001
        type: Bash
        execution:
          onExecute:
            - echo hello
      - name: S_Bash_Util_8631_002
        type: Bash
        execution:
          onExecute:
            - echo hello2
