pipelines:
  - name: taylorl
    steps:
      - name: taylorl_0001
        type: Bash
        configuration:
          integrations:
            - name: email
        execution:
          onExecute:
            - echo "executing step"
            - cat doesnotexist.txt
          onFailure:
            - echo \"Failed...\"
            - echo \"testing 1234\" && return 1
          onComplete:
            - send_notification email --recipients taylorl@jfrog.com --show-failing-commands
