resources:
  - name: res1
    type: GitRepo
    configuration:
      cloneProtocol: https
      path: ~taylorl/go-hello-world
      gitProvider: bitbucket
  - name: res2
    type: GitRepo
    configuration:
      cloneProtocol: https
      path: ~taylorl/automation-test-scripts
      gitProvider: bitbucket
  - name: res3
    type: GitRepo
    configuration:
      path: ~taylorl/controlplane
      cloneProtocol: https
      gitProvider: bitbucket
      branches:
        include: ^master$
      files:
        include: \b(tools\/ms-testing-library|packages\/types).*


pipelines:
  - name: taylorl
    steps:
      - name: taylorl_0001
        type: Bash
        configuration:
          inputResources:
            - name: res3
        execution:
          onExecute:
            - printenv
            - echo hello1
