pipelines:
  - name: taylorl
    configuration:
      affinityGroup: 'foo'
    steps:
      - name: taylorl_0001
        type: Bash
        execution:
          onExecute:
            - echo hello1
      - name: taylorl_0002
        type: Bash
        configuration:
          inputSteps:
            - name: taylorl_0001
        execution:
          onExecute:
            - echo hello2
