pipelines:
  - name: S_Bash_Util_6380_009
    steps:
      - name: S_Bash_Util_6380_009_1
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
            - name: int_token
        execution:
          onExecute:
            - configure_jfrog_cli --artifactory-url $int_s_artifactory_url --access-token $int_int_token_token --server-name test_config
            - jfrog config show test_config
          onComplete:
            - cleanup_jfrog_cli --server-name test_config
