pipelines:
  - name: taylorl
    steps:
      - name: taylorl_0001
        type: Bash
        configuration:
          inputResources:
            - name: int_email
        execution:
          onExecute:
            - echo hello
            - 2 == 1
          onFailure:
            - send_notification int_email taylorl@jfrog.com