pipelines:
  - name: email
    steps:
      - name: taylorl_0001
        type: Bash
        configuration:
          integrations:
            - name: int_email
        execution:
          onExecute:
            - echo hello
          onFailure:
            - send_notification int_email --recipients taylorl@jfrog.com
