resources:
  - name: res1
    type: GitRepo
    configuration:
      path: ~taylorl/go-hello-world
      gitProvider: bitbucket
  # - name: res2
  #   type: GitRepo
  #   configuration:
  #     path: SyntacticStructures/Org_test_Automation_bash
  #     gitProvider: s_gitHub
  

pipelines:
  - name: taylorl
    configuration:
      nodePool: 'w19'
    steps:
      - name: taylorl_0001
        type: PowerShell
        configuration:
          inputResources:
            - name: res1
            # - name: res2
        execution:
          onExecute:
            - echo hello1
