pipelines:
  - name: slack
    steps:
      - name: taylorl_0001
        type: Bash
        configuration:
          integrations:
            - name: int_slack
        execution:
          onExecute:
            - echo hello
          onFailure:
            - send_notification int_email --recipients taylorl@jfrog.com --show-failing-commands
