pipelines:
  - name: parent
    steps:
      - name: parent_0001
        type: TriggerPipeline
        configuration:
          pipelineName: child
          stepName: child_001
          waitForRunCompletion: false
          integrations:
            - name: artifactory
